<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">ls</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:0:required path</value>
    <value>[i] field:0:optional filter</value>
    <value>[o] field:1:required files</value>
  </array>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gLS0tIDw8SVMtQkVHSU4tUElQRUxJTkUtSU4+PiAtLS0KLy8gV0FSTklORzogQXV0byBnZW5l
cmF0ZSBjb2RlIHdpbGwgbm90IGJlIHByZXNlcnZlZCB1cG9uIEphdmEgc2lnbmF0dXJlIHVwZGF0
ZS4KLy8gRG8gbm90IGFkZCBjdXN0b20gY29kZSBoZXJlLgoKSURhdGFNYXAgcGlwZWxpbmVJbk1h
cCA9IG5ldyBJRGF0YU1hcChwaXBlbGluZSk7ClN0cmluZyBpbnB1dHBhdGggPSAoU3RyaW5nKSBw
aXBlbGluZUluTWFwLmdldCgicGF0aCIpOwpTdHJpbmcgaW5wdXRmaWx0ZXIgPSAoU3RyaW5nKSBw
aXBlbGluZUluTWFwLmdldCgiZmlsdGVyIik7Ci8vIC0tLSA8PElTLUVORC1QSVBFTElORS1JTj4+
IC0tLQoKLy8gLS0tIDw8SVMtQkVHSU4tSU5TVEFOQ0VTLVBJUEVMSU5FLU9VVD4+IC0tLQovLyBX
QVJOSU5HOiBBdXRvIGdlbmVyYXRlIGNvZGUgd2lsbCBub3QgYmUgcHJlc2VydmVkIHVwb24gSmF2
YSBzaWduYXR1cmUgdXBkYXRlLgovLyBEbyBub3QgYWRkIGN1c3RvbSBjb2RlIGhlcmUuCgpTdHJp
bmdbXSBvdXRwdXRmaWxlcyA9IG51bGw7Ci8vIC0tLSA8PElTLUVORC1JTlNUQU5DRVMtUElQRUxJ
TkUtT1VUPj4gLS0tCi8vIHByb2Nlc3MKCkZpbGUgZGlyID0gbmV3IEZpbGUoaW5wdXRwYXRoKTsK
CmlmIChkaXIuZXhpc3RzKCkpIHsKCWlmIChkaXIuaXNEaXJlY3RvcnkoKSkKCQlvdXRwdXRmaWxl
cyA9IGRpci5saXN0KG5ldyBGaWxlbmFtZUZpbHRlcigpIHsKCgkJCUBPdmVycmlkZQoJCQlwdWJs
aWMgYm9vbGVhbiBhY2NlcHQoRmlsZSBmaWxlLCBTdHJpbmcgZmlsZW5hbWUpIHsKCgkJCQlyZXR1
cm4gIWZpbGVuYW1lLnN0YXJ0c1dpdGgoIi4iKQoJCQkJCQkmJiAoaW5wdXRmaWx0ZXIgPT0gbnVs
bCB8fCBmaWxlbmFtZS50b0xvd2VyQ2FzZSgpLmNvbnRhaW5zKGlucHV0ZmlsdGVyLnRvTG93ZXJD
YXNlKCkpKTsKCQkJfQoJCX0pOwoJZWxzZQoJCXRocm93IG5ldyBTZXJ2aWNlRXhjZXB0aW9uKCJw
YXRoIGlzIG5vdCBhIGRpcmVjdG9yeToiICsgaW5wdXRwYXRoKTsKfSBlbHNlIHsKCXRocm93IG5l
dyBTZXJ2aWNlRXhjZXB0aW9uKCJEaXJlY3RvcnkgZG9lcyBub3QgZXhpc3Q6IiArIGlucHV0cGF0
aCk7Cn0KCi8vIC0tLSA8PElTLUJFR0lOLVBJUEVMSU5FLU9VVD4+IC0tLQovLyBXQVJOSU5HOiBB
dXRvIGdlbmVyYXRlIGNvZGUgd2lsbCBub3QgYmUgcHJlc2VydmVkIHVwb24gSmF2YSBzaWduYXR1
cmUgdXBkYXRlLgovLyBEbyBub3QgYWRkIGN1c3RvbSBjb2RlIGhlcmUuCgpJRGF0YU1hcCBwaXBl
bGluZU91dE1hcCA9IG5ldyBJRGF0YU1hcChwaXBlbGluZSk7CnBpcGVsaW5lT3V0TWFwLnB1dCgi
ZmlsZXMiLCBvdXRwdXRmaWxlcyk7Ci8vIC0tLSA8PElTLUVORC1QSVBFTElORS1PVVQ+PiAtLS0K
</value>
</Values>
