<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">ls</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:0:required path</value>
    <value>[i] field:0:required filter</value>
    <value>[o] field:1:required files</value>
  </array>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gLS0tIDw8SVMtQkVHSU4tUElQRUxJTkUtSU4+PiAtLS0KLy8gV0FSTklORzogQXV0byBnZW5l
cmF0ZSBjb2RlIHdpbGwgbm90IGJlIHByZXNlcnZlZCB1cG9uIEphdmEgc2lnbmF0dXJlIHVwZGF0
ZS4KLy8gRG8gbm90IGFkZCBjdXN0b20gY29kZSBoZXJlLgoKSURhdGFNYXAgcGlwZWxpbmVJbk1h
cCA9IG5ldyBJRGF0YU1hcChwaXBlbGluZSk7ClN0cmluZyBpbnB1dHBhdGggPSAoU3RyaW5nKSBw
aXBlbGluZUluTWFwLmdldCgicGF0aCIpOwpTdHJpbmcgaW5wdXRmaWx0ZXIgPSAoU3RyaW5nKSBw
aXBlbGluZUluTWFwLmdldCgiZmlsdGVyIik7Ci8vIC0tLSA8PElTLUVORC1QSVBFTElORS1JTj4+
IC0tLQoKLy8gLS0tIDw8SVMtQkVHSU4tSU5TVEFOQ0VTLVBJUEVMSU5FLU9VVD4+IC0tLQovLyBX
QVJOSU5HOiBBdXRvIGdlbmVyYXRlIGNvZGUgd2lsbCBub3QgYmUgcHJlc2VydmVkIHVwb24gSmF2
YSBzaWduYXR1cmUgdXBkYXRlLgovLyBEbyBub3QgYWRkIGN1c3RvbSBjb2RlIGhlcmUuCgpTdHJp
bmdbXSBvdXRwdXRmaWxlcyA9IG51bGw7Ci8vIC0tLSA8PElTLUVORC1JTlNUQU5DRVMtUElQRUxJ
TkUtT1VUPj4gLS0tCgkJLy8gcHJvY2VzcwoKCQlGaWxlIGRpciA9IG5ldyBGaWxlKGlucHV0cGF0
aCk7CgkJU3RyaW5nW10gZmlsZXM7CgkJCgkJaWYgKGRpci5leGlzdHMoKSkgewoJCQlpZiAoZGly
LmlzRGlyZWN0b3J5KCkpCgkJCQlmaWxlcyA9IGRpci5saXN0KG5ldyBGaWxlbmFtZUZpbHRlcigp
IHsKCQkJCQkKCQkJCQlAT3ZlcnJpZGUKCQkJCQlwdWJsaWMgYm9vbGVhbiBhY2NlcHQoRmlsZSBm
aWxlLCBTdHJpbmcgZmlsZW5hbWUpIHsKCQkJCQkJCgkJCQkJCXJldHVybiAhZmlsZW5hbWUuc3Rh
cnRzV2l0aCgiLiIpICYmIChpbnB1dGZpbHRlciA9PSBudWxsIHx8IGZpbGVuYW1lLnRvTG93ZXJD
YXNlKCkuY29udGFpbnMoaW5wdXRmaWx0ZXIudG9Mb3dlckNhc2UoKSkpOwoJCQkJCX0KCQkJCX0p
OwoJCQllbHNlCgkJCQl0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbigicGF0aCBpcyBub3QgYSBk
aXJlY3Rvcnk6IiArIGlucHV0cGF0aCk7CgkJfSBlbHNlIHsKCQkJdGhyb3cgbmV3IFNlcnZpY2VF
eGNlcHRpb24oIkRpcmVjdG9yeSBkb2VzIG5vdCBleGlzdDoiICsgaW5wdXRwYXRoKTsKCQl9CgkJ
Ci8vIC0tLSA8PElTLUJFR0lOLVBJUEVMSU5FLU9VVD4+IC0tLQovLyBXQVJOSU5HOiBBdXRvIGdl
bmVyYXRlIGNvZGUgd2lsbCBub3QgYmUgcHJlc2VydmVkIHVwb24gSmF2YSBzaWduYXR1cmUgdXBk
YXRlLgovLyBEbyBub3QgYWRkIGN1c3RvbSBjb2RlIGhlcmUuCgpJRGF0YU1hcCBwaXBlbGluZU91
dE1hcCA9IG5ldyBJRGF0YU1hcChwaXBlbGluZSk7CnBpcGVsaW5lT3V0TWFwLnB1dCgiZmlsZXMi
LCBvdXRwdXRmaWxlcyk7Ci8vIC0tLSA8PElTLUVORC1QSVBFTElORS1PVVQ+PiAtLS0K</value>
</Values>
