<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">readFile</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:0:required fname</value>
    <value>[i] field:0:required loadAs</value>
    <value>[i] field:0:required ignoreError</value>
    <value>[o] field:0:required name</value>
    <value>[o] object:0:required bytes</value>
    <value>[o] field:0:required string</value>
    <value>[o] object:0:required stream</value>
  </array>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gLS0tIDw8SVMtQkVHSU4tUElQRUxJTkUtSU4+PiAtLS0KLy8gV0FSTklORzogQXV0byBnZW5l
cmF0ZSBjb2RlIHdpbGwgbm90IGJlIHByZXNlcnZlZCB1cG9uIEphdmEgc2lnbmF0dXJlIHVwZGF0
ZS4KLy8gRG8gbm90IGFkZCBjdXN0b20gY29kZSBoZXJlLgoKSURhdGFNYXAgcGlwZWxpbmVJbk1h
cCA9IG5ldyBJRGF0YU1hcChwaXBlbGluZSk7CklEYXRhQ3Vyc29yIGMgPSBwaXBlbGluZS5nZXRD
dXJzb3IoKTsKU3RyaW5nIGlucHV0Zm5hbWUgPSAoU3RyaW5nKSBwaXBlbGluZUluTWFwLmdldCgi
Zm5hbWUiKTsKU3RyaW5nIGlucHV0bG9hZEFzID0gKFN0cmluZykgcGlwZWxpbmVJbk1hcC5nZXQo
ImxvYWRBcyIpOwpTdHJpbmcgaW5wdXRpZ25vcmVFcnJvciA9IChTdHJpbmcpIHBpcGVsaW5lSW5N
YXAuZ2V0KCJpZ25vcmVFcnJvciIpOwovLyAtLS0gPDxJUy1FTkQtUElQRUxJTkUtSU4+PiAtLS0K
Ci8vIC0tLSA8PElTLUJFR0lOLUlOU1RBTkNFUy1QSVBFTElORS1PVVQ+PiAtLS0KLy8gV0FSTklO
RzogQXV0byBnZW5lcmF0ZSBjb2RlIHdpbGwgbm90IGJlIHByZXNlcnZlZCB1cG9uIEphdmEgc2ln
bmF0dXJlIHVwZGF0ZS4KLy8gRG8gbm90IGFkZCBjdXN0b20gY29kZSBoZXJlLgoKU3RyaW5nIG91
dHB1dG5hbWUgPSBudWxsOwpieXRlW10gb3V0cHV0Ynl0ZXMgPSBudWxsOwpTdHJpbmcgb3V0cHV0
c3RyaW5nID0gbnVsbDsKT2JqZWN0IG91dHB1dHN0cmVhbSA9IG51bGw7Ci8vIC0tLSA8PElTLUVO
RC1JTlNUQU5DRVMtUElQRUxJTkUtT1VUPj4gLS0tCmJ5dGVbXSBkYXRhID0gbnVsbDsKSW5wdXRT
dHJlYW0gaW4gPSBudWxsOwoKdHJ5IHsKCWlmIChpbnB1dGxvYWRBcyAhPSBudWxsICYmIGlucHV0
bG9hZEFzLmVxdWFsc0lnbm9yZUNhc2UoInN0cmVhbSIpKSB7CgkJaW4gPSBuZXcgRmlsZUlucHV0
U3RyZWFtKG5ldyBGaWxlKGlucHV0Zm5hbWUpKTsKCX0gZWxzZSB7CgkJZGF0YSA9IEZpbGVzLnJl
YWRBbGxCeXRlcyhQYXRocy5nZXQoaW5wdXRmbmFtZSkpOwoJfQp9IGNhdGNoIChOb1N1Y2hGaWxl
RXhjZXB0aW9uIGUgKSB7CglpZiAoaW5wdXRpZ25vcmVFcnJvciA9PSBudWxsIHx8ICFpbnB1dGln
bm9yZUVycm9yLmVxdWFsc0lnbm9yZUNhc2UoInRydWUiKSkKCQl0aHJvdyBuZXcgU2VydmljZUV4
Y2VwdGlvbihlKTsKfSBjYXRjaCAoSU9FeGNlcHRpb24gZSkgewoJCgl0aHJvdyBuZXcgU2Vydmlj
ZUV4Y2VwdGlvbihlKTsKfQoKLy8gcGlwZWxpbmUgb3V0CgpJRGF0YVV0aWwucHV0KGMsICJuYW1l
IiwgbmV3IEZpbGUoaW5wdXRmbmFtZSkuZ2V0TmFtZSgpKTsKCmlmIChkYXRhICE9IG51bGwpIHsK
CQoJaWYgKGlucHV0bG9hZEFzICE9IG51bGwgJiYgaW5wdXRsb2FkQXMuZXF1YWxzSWdub3JlQ2Fz
ZSgic3RyaW5nIikpCgkJSURhdGFVdGlsLnB1dChjLCAic3RyaW5nIiwgbmV3IFN0cmluZyhkYXRh
KSk7CgllbHNlCgkJSURhdGFVdGlsLnB1dChjLCAiYnl0ZXMiLCBkYXRhKTsKCWMuZGVzdHJveSgp
Owp9IGVsc2UgewoJSURhdGFVdGlsLnB1dChjLCAic3RyZWFtIiwgaW4pOwp9Ci8vIC0tLSA8PElT
LUJFR0lOLVBJUEVMSU5FLU9VVD4+IC0tLQovLyBXQVJOSU5HOiBBdXRvIGdlbmVyYXRlIGNvZGUg
d2lsbCBub3QgYmUgcHJlc2VydmVkIHVwb24gSmF2YSBzaWduYXR1cmUgdXBkYXRlLgovLyBEbyBu
b3QgYWRkIGN1c3RvbSBjb2RlIGhlcmUuCgpJRGF0YU1hcCBwaXBlbGluZU91dE1hcCA9IG5ldyBJ
RGF0YU1hcChwaXBlbGluZSk7CnBpcGVsaW5lT3V0TWFwLnB1dCgibmFtZSIsIG91dHB1dG5hbWUp
OwpwaXBlbGluZU91dE1hcC5wdXQoImJ5dGVzIiwgb3V0cHV0Ynl0ZXMpOwpwaXBlbGluZU91dE1h
cC5wdXQoInN0cmluZyIsIG91dHB1dHN0cmluZyk7CnBpcGVsaW5lT3V0TWFwLnB1dCgic3RyZWFt
Iiwgb3V0cHV0c3RyZWFtKTsKLy8gLS0tIDw8SVMtRU5ELVBJUEVMSU5FLU9VVD4+IC0tLQo=</value>
</Values>
