<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">sleep</value>
  <value name="encodeutf8">true</value>
  <value name="body">CQkvLyAtLS0gPDxJUy1CRUdJTi1QSVBFTElORS1JTj4+IC0tLQoJCS8vIFdBUk5JTkc6IEF1dG8g
Z2VuZXJhdGUgY29kZSB3aWxsIG5vdCBiZSBwcmVzZXJ2ZWQgdXBvbiBKYXZhIHNpZ25hdHVyZSB1
cGRhdGUuCgkJLy8gRG8gbm90IGFkZCBjdXN0b20gY29kZSBoZXJlLgoKCQlJRGF0YU1hcCBwaXBl
bGluZUluTWFwID0gbmV3IElEYXRhTWFwKHBpcGVsaW5lKTsKCQlTdHJpbmcgaW5wdXRkZWxheSA9
IChTdHJpbmcpIHBpcGVsaW5lSW5NYXAuZ2V0KCJkZWxheSIpOwoJCS8vIC0tLSA8PElTLUVORC1Q
SVBFTElORS1JTj4+IC0tLQoJCXRyeSB7CgkJCVRocmVhZC5zbGVlcChMb25nLnBhcnNlTG9uZyhp
bnB1dGRlbGF5KSk7CgkJfSBjYXRjaCAoTnVtYmVyRm9ybWF0RXhjZXB0aW9uIGUpIHsKCQkJZS5w
cmludFN0YWNrVHJhY2UoKTsKCQl9IGNhdGNoIChJbnRlcnJ1cHRlZEV4Y2VwdGlvbiBlKSB7CgkJ
CWUucHJpbnRTdGFja1RyYWNlKCk7CgkJfQ==</value>
</Values>
