version: "1.0"
info:
  model: int-scaffold
packages:
- name: JlGithubProject
  gitServerName: gitJl
  gitUrl: https://github.com/levjason/JlGithubProject
  gitUsername: levjason
  gitBranch: main
services:
- serviceName: project.jlgithub.javaservices.Default:copy
  packages:
  - name: JlGithubProject
    version: "1.0"
- serviceName: project.jlgithub.javaservices:copy
  packages:
  - name: JlGithubProject
    version: "1.0"
- serviceName: project.jlgithub.javaservices.Default:ls
  packages:
  - name: JlGithubProject
    version: "1.0"
- serviceName: project.jlgithub.javaservices:ls
  packages:
  - name: JlGithubProject
    version: "1.0"
- serviceName: project.jlgithub.javaservices:sleep
  packages:
  - name: JlGithubProject
    version: "1.0"
